//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Election
    {
        public int ID { get; set; }
        public string TypeOfElection { get; set; }
        public string State { get; set; }
        public Nullable<int> Date { get; set; }
        public string AreaName { get; set; }
        public string AreaType { get; set; }
        public Nullable<int> TotalVotes { get; set; }
        public Nullable<int> RepublicanVotes { get; set; }
        public string RepublicanCand { get; set; }
        public Nullable<int> DemocraticVotes { get; set; }
        public string DemocraticCand { get; set; }
        public string ThirdParty { get; set; }
        public string ThirdPartyVotes { get; set; }
        public string ThirdPartyCand { get; set; }
        public Nullable<int> OtherVotes { get; set; }
    }
}
